# Name of the workflow
name: Test and benchmark models 

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    
    - name: Test and benchmark models
      id: test_benchmark
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        REGION: ${{ secrets.REGION }}

      run: |
        python3 -m pip install --upgrade pip
        pip install -r ./dependencies/requirements.txt
        python -m spacy download en_core_web_sm
        python ./scripts/stage_model_to_production.py

