# Name of the workflow
name: Test and benchmark models 

on: workflow_dispatch

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    
    - name: Test and benchmark models
      id: test_benchmark
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        REGION: ${{ secrets.REGION }}

      run: |
        pip install --user --upgrade pip
        pip install -r /requirements.txt
        python ./scripts/stage_model_to_production.py

